export type InventoryCountFailure =
  | 'IDEMPOTENCY_KEY_INVALID'
  | 'IDEMPOTENCY_KEY_REQUIRED'
  | 'IDEMPOTENCY_KEY_REUSED'
  | 'INVENTORY_COUNT_ADJUSTMENT_FAILED'
  | 'INVENTORY_COUNT_APPROVER_CANNOT_ADJUST'
  | 'INVENTORY_COUNT_BALANCE_CHANGED'
  | 'INVENTORY_COUNT_CONFLICT'
  | 'INVENTORY_COUNT_INVALID_STATE'
  | 'INVENTORY_COUNT_LINE_ALREADY_CAPTURED'
  | 'INVENTORY_COUNT_NEGATIVE_BALANCE'
  | 'INVENTORY_COUNT_PERMISSION_DENIED'
  | 'INVENTORY_COUNT_PRODUCT_NOT_FOUND'
  | 'INVENTORY_COUNT_REQUEST_INVALID'
  | 'INVENTORY_COUNT_REQUIRES_LINES'
  | 'INVENTORY_COUNT_SESSION_NOT_FOUND'
  | 'INVENTORY_COUNT_WAREHOUSE_NOT_FOUND'
  | 'INVENTORY_COUNT_WAREHOUSE_OUT_OF_SCOPE';

export class InventoryCountError extends Error {
  constructor(readonly code: InventoryCountFailure) {
    super(code);
    this.name = 'InventoryCountError';
  }
}
