packages:
  - apps/*
  - packages/*

allowBuilds:
  '@prisma/engines': true
  '@scarf/scarf': false
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - globals@17.9.0
  - tsx@4.23.4
